### PR TITLE
exception fixes & convertion to nullptr

### PR DESCRIPTION
**Pull request by hirdrac**
touches lots of files but the changes are straightforward

### CODE REVIEW

**Comment by zaimoni** [comment]
I will have to document there's a warning re the archaic null pointer constant 0 to be aware of, in coding standards.

Also: does your development environment try to calculate the actual return type of functions of return type auto?  [Need to decide whether there's a pragmatic reason to avoid re-adding a static cast to re-enable that for npc::find_alive, npc::find_alive_r ... will catch this on my end if indicated.]

**Comment by hirdrac** [comment]
I just changed those functions by hand.  Basically, I try to avoid auto for function return types unless I'm making template/generic code.  Just trying to make it easier so I don't have to spend an extra second or so to figure out the return type if I use the functions. :)

**Comment by zaimoni** [comment]
For these functions it's not material: there is no foreseeable legitimate refactoring that would cause a cascade return type change.   (I will waste time involuntarily verifying the return type is consistent; auto return bypasses that compulsion.)

**Comment by hirdrac** [comment]
Well, if it's just a numeric type I see your point (and those are good candidates for templates) but I think it's important to see pointer/reference (w/wo const) in the function definition.  But, you know, it's your project so do what you want.

I suppose I should bring up my next task was going to be purging all the defines/macros ;)

**Comment by zaimoni** [comment]
Thus, code locality.

Release happens *before* the first functionally risky commit (and many of the #define alterations would be such, especially with the current struct differences between Socrates' Daimon and Cataclysm).

**Comment by hirdrac** [comment]
I'll ease back on the clean up until after you've made your official release

**Comment by zaimoni** [comment]
re defines...there's also some strategic issues (i.e., proper roadmap indicated; alternately, systems analysis needed).

**Comment by zaimoni** [comment]
Sketch at https://github.com/zaimoni/Cataclysm/issues/66 .

**Pull request merged**
