### PR TITLE
fix for divide-by-zero crash when adjusting recoil

### PR DESCRIPTION
**Pull request by hirdrac**
Haven't had any other crashes since I fixed this so far - I can actually play until I get killed by a zombie :)

### CODE REVIEW

**Comment by zaimoni** [comment]
Conservative...will merge then restore pre-micro-optimization behavior

**Comment by hirdrac** [comment]
No worries - I saw you had changed the logic but I didn't know if that's what you intended or not.
Anyways, I managed to get another 'npc::execute_action will fail' exception so more work to do tracking down issues.

**Comment by zaimoni** [comment]
Reviewing: The NPC AI was parked in the middle of a very invasive AI re-specification.  The ai_action typedef is a bridge between:

* the legacy AI (which uses the C enumeration npc_action, defined in npc.h)
** historically, the npc_undecided enum value (0) was a precondition failure for npc::execute_action; when I installed the logic error exception in debug builds I removed multiple precondition checks for it in individual handler functions.  Release mode builds should just noisily no-op (one debug message "unknown npc action" per turn).

* the re-specified AI (which uses action objects; these are subclasses of the abstract class action, defined in act_obj.h)

The action class's specification was copied from Rogue Survivor Revived's ActorAction object.  Rogue Survivor Revived uses the entire interface. (The distinction between IsLegal and IsPerformable is because Rogue Survivor Revived can schedule actions for later turns; obviously some JSON support would have to be built out for that to be meaningful here.)

**Comment by hirdrac** [comment]
Perhaps a debug log would be a better way to handle this sort of error - it could capture more detail about object states and allows users to give you more information when reporting problems.

**Comment by zaimoni** [comment]
It depends on the development environment.  What I do know, is that the way the inherited debugmsg (over in output.cpp) works doesn't mesh well with what I find useful.

The hard-coded std::logic_error throws went in before the compile-time option that allows switching the assert re-implementation in Zaimoni.STL/Logging.h to them.  They should all be within #ifndef NDEBUG blocks.  They're specifically useful when throwing an exception will land in a debugger (and thus give a browsable stack trace with moderately complete object states); I'm not sure how to arrange that on *NIX.

I think this rates its own issue ... design work may be too complex to schedule before the 0.2.3 release, even if it can be reduced to proofreadable formal transforms.  [We're in the planned release window, but as long as we don't need to land any destabilizing changes I'm fine pushing off the release as late as August 31 2020].

**Comment by zaimoni** [comment]
Sketch at https://github.com/zaimoni/Cataclysm/issues/63 .

**Pull request merged**
